# Generated by Django 2.1.7 on 2019-04-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190401_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncodedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('encoded_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScanData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoded_text', models.CharField(max_length=50)),
                ('user_position', models.CharField(max_length=20)),
            ],
        ),
    ]
